import './globals.css'
import { Inter, Montserrat } from 'next/font/google'
import Link from 'next/link'
import DarkMode from '@components/darkmode'

const montserrat = Montserrat({ subsets: ['latin'], preload: true, weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] })
const inter = Inter({ subsets: ['latin'], preload: true, weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] })

export const metadata = {
  title: 'Public transport service | Hermes',
  description: 'Generated by create next app',
}

const mask = 'linear-gradient(to bottom, rgba(0, 0, 0, 1) 0%, rgba(0, 0, 0, 1) 60%, rgba(0, 0, 0, 0) 100%)'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body className={`h-screen w-screen dark:bg-background/dark`}>
        <noscript className='w-screen h-screen fixed flex items-center backdrop-blur-xl z-[999] select-none'>
          <div className="flex flex-col items-center w-full">
            <h1 className={`${montserrat.className} text-4xl font-black text-center w-full dark:text-slate-100`}>
              Esta página necessita de <wbr />JavaScript para funcionar
            </h1>
            <p className={`${inter.className} font-extrabold text-2xl dark:text-slate-100`}>Aprenda como ativar <a
              href="https://support.google.com/adsense/answer/12654?hl=pt-BR"
              className={`${inter.className} text-cyan-400 font-black hover:underline`}
              style={{ textDecorationThickness: '.1rem' }}
              target="_blank"
              rel="noopener noreferrer"
            >aqui</a></p>
          </div>
        </noscript>
        <header className='sticky top-0 w-screen max-md:px-5 md:px-20 max-md:pt-4 md:pt-8 inline-flex select-none items-center justify-between z-[900]'>
          <div className='absolute top-0 left-0 w-full h-[175%] backdrop-blur-lg -z-10' style={{
            maskImage: mask,
            WebkitMaskImage: mask,
          }} />
          <Link className={`${montserrat.className} flex flex-row items-center`} href="/">
            <span className={`font-black dark:text-white max-md:text-xl md:text-4xl`}>Hermes</span>
            <span className={`max-md:text-[0.65rem] md:text-sm font-black md:translate-y-0.5 px-2 p-0.5 rounded-xl max-md:ml-1 md:ml-3 bg-gradient-to-br from-fuchsia-600 via-fuchsia-700 to-violet-600 text-white`}>ALPHA</span>
          </Link>
          <div className='inline-flex justify-evenly w-full'>
            <Link
              href='/routes'
              className='font-bold dark:text-slate-300 hover:underline underline-offset-4'
              style={{ textDecorationThickness: '.1rem' }}
              draggable={false}
            >Rotas</Link>
          </div>
          <div className="flex flex-row items-center justify-around">
            <DarkMode />
            <Link
              href='/login'
              className='font-bold dark:text-slate-300 max-md:mr-4 hover:underline underline-offset-4'
              style={{ textDecorationThickness: '.1rem' }}
              draggable={false}
            >Login</Link>
          </div>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
