import '@globalcss'
import { Inter, Montserrat } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'], preload: true, weight: ["900"] })
const inter = Inter({ subsets: ['latin'], preload: true, weight: ["400", "500", "600"] })

export const metadata = {
  title: 'Public transport service | Hermes',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=''>
      <body className={`${inter.className}`}>{children}</body>
    </html>
  )
}
